// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetStartURL():Promise<string>;

export function GetUserDataDir():Promise<string>;

export function GoBack():Promise<void>;

export function GoForward():Promise<void>;

export function HardReload():Promise<void>;

export function IsInternalURL(arg1:string):Promise<boolean>;

export function Minimise():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<boolean>;

export function Quit():Promise<void>;

export function Reload():Promise<void>;

export function ResetZoom():Promise<void>;

export function SaveCurrentWindowState():Promise<void>;

export function ToggleMaximise():Promise<void>;

export function ZoomIn():Promise<void>;

export function ZoomOut():Promise<void>;
