// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetStartURL() {
  return window['go']['main']['App']['GetStartURL']();
}

export function GetUserDataDir() {
  return window['go']['main']['App']['GetUserDataDir']();
}

export function GoBack() {
  return window['go']['main']['App']['GoBack']();
}

export function GoForward() {
  return window['go']['main']['App']['GoForward']();
}

export function HardReload() {
  return window['go']['main']['App']['HardReload']();
}

export function IsInternalURL(arg1) {
  return window['go']['main']['App']['IsInternalURL'](arg1);
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function ResetZoom() {
  return window['go']['main']['App']['ResetZoom']();
}

export function SaveCurrentWindowState() {
  return window['go']['main']['App']['SaveCurrentWindowState']();
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function ZoomIn() {
  return window['go']['main']['App']['ZoomIn']();
}

export function ZoomOut() {
  return window['go']['main']['App']['ZoomOut']();
}
